## Google Colab Kullanımı

1. Google Colab Kullanımı
2. Makine Öğrenmesi İçin Python Temelleri
3. Temel Makine Öğrenmesi Kavramları








In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 1. Makine Öğrenmesi için Python Temelleri
Numpy, Pandas ile Temel İşlemler



## Numpy ile Çalışmak
**Numpy Nedir?**
Numpy, bilimsel hesaplamalar için geliştirilmiş bir Python kütüphanesidir ve özellikle büyük veri üzerinde hızlı matematiksel işlemler yapmayı sağlar.
Numpy’ın en temel veri yapısı olan "ndarray" adı verilen çok boyutlu dizi yapısı, verilerin bellekte düzenli bir şekilde saklanmasına olanak tanır. Bu dizi yapıları, büyük veri analizlerinde daha hızlı işlem yapmamızı sağlar.

**Numpy’ın Sağladığı Avantajlar**
1. **Performans**: Numpy, Python’ın yerleşik listelerinden çok daha hızlı çalışır. Veriyi bellekte daha verimli bir şekilde saklayarak işlemleri hızlandırır. Bu hız, özellikle büyük veri setleri üzerinde çalışırken büyük avantaj sağlar.
2. **Matematiksel İşlemler**: Numpy, doğrusal cebir işlemleri, matris çarpımları, istatistiksel hesaplamalar gibi bilimsel ve mühendislik hesaplamalarını kolaylaştıran çok sayıda fonksiyon içerir.
3. **Veri Manipülasyonu**: Veriyi düzenleme, dilimleme, dönüştürme, filtreleme gibi işlemler Numpy ile oldukça hızlı ve kolay bir şekilde yapılır. Bu özellikler, veri biliminde veriyi analiz edilebilir hale getirmek için oldukça önemlidir.

**Numpy Nerelerde Kullanılır?**
1. **Veri Bilimi ve Makine Öğrenmesi**: Veri bilimi ve makine öğrenmesi projelerinde Numpy çok sık kullanılır. Veri üzerinde yapılan işlemler, veri temizleme ve hazırlama süreçlerinde hız ve kolaylık sağlar.
2. **Matematiksel ve İstatistiksel Hesaplamalar**: Bilimsel araştırmalarda doğrusal cebir, olasılık ve istatistiksel hesaplamalar için kullanılır. Bu tür işlemler, Numpy ile hızlı ve hassas bir şekilde yapılabilir.
3. **Görüntü İşleme**: Görüntüler, piksel verileri ile ifade edilir ve bu veriler Numpy dizileri şeklinde saklanır. Görüntü işleme kütüphaneleri, Numpy’yi kullanarak görüntü verilerini işler.
4. **Finansal Analiz ve Simülasyon**: Büyük finansal veri setleri üzerinde yapılan analizlerde ve simülasyon işlemlerinde Numpy yaygın olarak kullanılır. Rastgele sayı üretimi gibi özellikleri ile simülasyonlar ve modellemelerde işlevseldir.

**Numpy’nin Diğer Kütüphanelerle İlişkisi**
Numpy, diğer birçok veri bilimi kütüphanesi için temel bir araçtır. Örneğin, veri işleme için kullanılan Pandas kütüphanesi, Numpy yapılarını temel alır. Görselleştirme için kullanılan Matplotlib ve veri işleme için kullanılan Scikit-Learn gibi kütüphaneler de Numpy ile çalışır. Bu yüzden, Numpy’yi öğrenmek diğer kütüphaneleri kullanmayı da kolaylaştırır.

**Özetle**, Numpy, veri bilimi ve mühendislik hesaplamalarında hız, verimlilik ve esneklik sağlayan bir kütüphanedir. Çok boyutlu dizileri kullanarak veriyi daha iyi organize eder ve karmaşık matematiksel işlemleri kolaylaştırır. Bu nedenle, Numpy veri bilimciler, mühendisler ve araştırmacılar arasında çok popülerdir.

In [2]:
import numpy as np
# Numpy Array (Dizi) Oluşturma
# Numpy'da en temel veri yapısı "ndarray" dir.
array_1d = np.array([1, 2, 3, 4, 5])  # Tek boyutlu dizi
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # İki boyutlu dizi
print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)



1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Array Özellikleri
print("Array Boyutu (shape):", array_2d.shape)
print("Array Eleman Sayısı (size):", array_2d.size)
print("Array Veri Tipi (dtype):", array_2d.dtype)



Array Boyutu (shape): (2, 3)
Array Eleman Sayısı (size): 6
Array Veri Tipi (dtype): int64


In [4]:
# Dizi ile Temel Matematiksel İşlemler
array_sum = array_1d + 10  # Her elemana 10 ekle
array_square = array_1d ** 2  # Her elemanın karesi
print("Array + 10:", array_sum)
print("Array'in Karesi:", array_square)



Array + 10: [11 12 13 14 15]
Array'in Karesi: [ 1  4  9 16 25]


In [5]:
# Özel Diziler Oluşturma
zeros_array = np.zeros((3, 3))  # Sıfırlardan oluşan 3x3 matris
ones_array = np.ones((2, 2))  # Birlerden oluşan 2x2 matris
random_array = np.random.rand(3, 3)  # 3x3 rastgele sayı matrisi
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)
print("Random Array:\n", random_array)



Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Random Array:
 [[0.34567307 0.50917426 0.07806991]
 [0.03499748 0.35263907 0.19715894]
 [0.46537777 0.08591666 0.93343592]]


## Pandas ile Çalışmak
**Pandas**, Python programlama dili için geliştirilmiş, veri işleme ve analizinde kullanılan popüler bir kütüphanedir. Özellikle tablo şeklindeki (satır ve sütunlardan oluşan) veri üzerinde hızlı ve esnek bir şekilde çalışmayı sağlar. Pandas, veri analizi, veri temizleme, veri dönüştürme gibi işlemleri kolaylaştırır ve bu yüzden veri bilimi alanında temel bir araç olarak kabul edilir.

### Pandas’ın Özellikleri
1. **DataFrame Yapısı**: Pandas’ın en güçlü veri yapısı olan "DataFrame", Excel veya SQL tablolarına benzeyen, satır ve sütunlardan oluşan bir veri yapısıdır. DataFrame, tablo şeklinde organize edilmiş veriler üzerinde esnek bir şekilde çalışmamızı sağlar.
2. **Kolay Veri Manipülasyonu**: Pandas, verileri filtreleme, gruplama, sıralama, birleştirme gibi işlemleri kolayca yapabilmemizi sağlar. Bu işlemler, veriyi analiz edilebilir hale getirmede önemli adımlardır.
3. **Eksik Veri İşleme**: Gerçek hayattan gelen veri genellikle eksik veya hatalıdır. Pandas, eksik veriyi tespit etme ve doldurma gibi işlemleri hızlı bir şekilde yapabilmemizi sağlar.
4. **Geniş Dosya Format Desteği**: Pandas, veriyi farklı formatlarda (CSV, Excel, SQL, JSON, vb.) içe aktarma ve dışa aktarma imkanı sunar. Bu özellik, veri kaynakları arasında kolay geçiş yapmayı sağlar.

### Pandas’ın Kullanım Alanları
1. **Veri Bilimi ve Makine Öğrenmesi**: Pandas, veri biliminde en çok kullanılan kütüphanelerden biridir. Veriyi temizlemek, dönüştürmek, analiz etmek ve görselleştirmek için kullanılır. Makine öğrenmesi modellerini eğitmeden önce veriyi hazırlamak ve özellik mühendisliği yapmak için temel bir araçtır.
   
2. **Finansal Analiz**: Finansal veriler genellikle tarih bazında düzenlenmiştir ve Pandas bu tür veri üzerinde çalışmak için ideal bir araçtır. Pandas, zaman serisi analizleri, finansal göstergelerin hesaplanması, hisse senedi veya diğer finansal verilerin analizi için sıkça kullanılır.

3. **Veri Manipülasyonu ve Dönüştürme**: Pandas, büyük veri setleri üzerinde filtreleme, sıralama, gruplama gibi işlemler yaparak veriyi analiz edilebilir hale getirir. Bu nedenle, araştırma çalışmaları ve veri hazırlama süreçlerinde tercih edilir.

4. **İstatistiksel Analiz ve Raporlama**: Pandas, veri üzerinde hızlı istatistiksel hesaplamalar yapmamıza olanak tanır. Örneğin, veri setindeki ortalama, medyan, standart sapma gibi istatistiksel ölçütleri kolayca hesaplayabiliriz. Bu özellikler, raporlama ve analizlerde önemli bir rol oynar.

5. **Veri Görselleştirme**: Pandas, Matplotlib ve Seaborn gibi kütüphanelerle uyumlu çalışarak veriyi görselleştirmeye uygun hale getirir. Veri analiz sonuçlarını grafiklerle sunmak, veri bilimi projelerinde önemli bir adımdır.

### Pandas’ın Sağladığı Önemli İşlemler
- **Veriyi İçe ve Dışa Aktarma**: Pandas, CSV, Excel, SQL gibi farklı dosya formatlarından veri çekebilir ve bu formatlarda veri kaydedebilir. Bu özellik, veriyi farklı kaynaklardan almak ve analiz etmek için çok kullanışlıdır.
- **Filtreleme ve Seçim**: Belirli kriterlere göre satır veya sütunları seçme, filtreleme işlemlerini kolaylaştırır.
- **Gruplama ve Özetleme**: Veriyi belirli bir kategoriye göre gruplandırabilir ve her grup için istatistiksel özet çıkarabiliriz (örneğin, cinsiyete göre yaş ortalaması).
- **Eksik Verilerin İşlenmesi**: Eksik veriyi bulma, doldurma veya kaldırma işlemleri ile temiz bir veri seti oluşturabiliriz.
- **Zaman Serisi Analizi**: Pandas, tarih ve saat verileri ile çalışmak için özel fonksiyonlara sahiptir ve bu özellikler zaman serisi verileri analiz etmeyi kolaylaştırır.

### Özetle
Pandas, veri bilimi, finansal analiz, istatistiksel analiz gibi alanlarda kullanılan çok güçlü ve esnek bir araçtır. Özellikle tablo şeklindeki veriyi yönetmek, analiz etmek ve dönüştürmek için yaygın olarak kullanılır. Pandas, Python’da veri işleme süreçlerini kolaylaştırarak, veri bilimcilerin ve analistlerin hızlı ve verimli bir şekilde çalışmasına olanak tanır.

In [7]:

# Pandas, veri analizi ve veri manipülasyonu için kullanılan bir kütüphanedir.
import pandas as pd

# DataFrame Oluşturma
data = {'Ad': ['Ali', 'Ayşe', 'Ahmet', 'Mehmet'], 'Yaş': [23, 21, 25, 24], 'Cinsiyet': ['Erkek', 'Kadın', 'Erkek', 'Erkek']}
df = pd.DataFrame(data)
display("Pandas DataFrame:\n", df)



'Pandas DataFrame:\n'

Ad  Yaş Cinsiyet
0     Ali   23    Erkek
1    Ayşe   21    Kadın
2   Ahmet   25    Erkek
3  Mehmet   24    Erkek

In [9]:
# DataFrame Özellikleri ve İlk Analizler
display(df.dtypes)

Ad          object
Yaş          int64
Cinsiyet    object
dtype: object

In [ ]:
df.head() # İlk 2 satırı görüntüleme


     Ad  Yaş Cinsiyet
0   Ali   23    Erkek
1  Ayşe   21    Kadın
       Ad  Yaş Cinsiyet
2   Ahmet   25    Erkek
3  Mehmet   24    Erkek


In [ ]:
print(df.tail(2)) #son iki satırı görüntüleme


In [ ]:
print(df.shape)

(4, 3)


In [ ]:
# Temel İşlemler
print(df['Yaş'])  # Belirli bir kolonu seçme

0    23
1    21
2    25
3    24
Name: Yaş, dtype: int64


In [ ]:
print(df[['Ad', 'Yaş']])  # Birden fazla kolon seçme

       Ad  Yaş
0     Ali   23
1    Ayşe   21
2   Ahmet   25
3  Mehmet   24


In [ ]:
# Yeni Kolon Eklemek
df['Medeni Durum'] = ['Bekar', 'Evli', 'Bekar','Bekar']

In [ ]:
display("\nYeni Kolon Eklendi:\n", df)

'\nYeni Kolon Eklendi:\n'

Ad  Yaş Cinsiyet Medeni Durum
0     Ali   23    Erkek        Bekar
1    Ayşe   21    Kadın         Evli
2   Ahmet   25    Erkek        Bekar
3  Mehmet   24    Erkek        Bekar

In [ ]:
df.shape

(4, 4)

In [ ]:
# Satır ve Kolonları Filtreleme
display(df[df['Yaş'] > 23])

Ad  Yaş Cinsiyet Medeni Durum
2   Ahmet   25    Erkek        Bekar
3  Mehmet   24    Erkek        Bekar

In [ ]:
display(df[(df['Cinsiyet'] == 'Erkek') & (df['Yaş'] > 23)])

Ad  Yaş Cinsiyet Medeni Durum
2   Ahmet   25    Erkek        Bekar
3  Mehmet   24    Erkek        Bekar

In [ ]:
# Eksik Verileri Tespit Etme ve İşleme
df.loc[1, 'Yaş'] = np.nan  # Ayşe'nin yaşını bilinmeyen olarak işaretleyelim

In [ ]:
print("\nEksik Veri İçeren DataFrame:\n", df)


Eksik Veri İçeren DataFrame:
        Ad   Yaş Cinsiyet Medeni Durum
0     Ali  23.0    Erkek        Bekar
1    Ayşe   NaN    Kadın         Evli
2   Ahmet  25.0    Erkek        Bekar
3  Mehmet  24.0    Erkek        Bekar


In [ ]:
df.isnull()

Ad              0
Yaş             1
Cinsiyet        0
Medeni Durum    0
dtype: int64

In [ ]:
print(df['Ad'].isnull().any())

False


##derste açıklanan bonus

In [ ]:
eksik_veri_satirlari = df[df.isnull().any(axis=1)] #1 satır çalıştırır, 0 sütun çalıştırır
print(eksik_veri_satirlari)
sadece_ali_eksik = (eksik_veri_satirlari["Ad"] == "Ali").all()
print(sadece_ali_eksik)

     Ad  Yaş Cinsiyet Medeni Durum
1  Ayşe  NaN    Kadın         Evli
False


In [ ]:
df[df["Ad"] == "Ali"].isnull().any(axis=1)

0    False
dtype: bool

In [ ]:
print(df.isnull().sum())

Ad              0
Yaş             1
Cinsiyet        0
Medeni Durum    0
dtype: int64


In [ ]:
# Eksik Verileri Doldurma
df['Yaş'] = df['Yaş'].fillna(df['Yaş'].mean())  # Eksik verileri yaş ortalaması ile doldurma

In [ ]:
display( df)

Ad   Yaş Cinsiyet Medeni Durum
0     Ali  23.0    Erkek        Bekar
1    Ayşe  24.0    Kadın         Evli
2   Ahmet  25.0    Erkek        Bekar
3  Mehmet  24.0    Erkek        Bekar

In [ ]:
# DataFrame Üzerinde Gruplama ve İstatistiksel İşlemler
grouped_data = df.groupby('Cinsiyet')['Yaş'].mean()

In [ ]:
print( grouped_data)

Cinsiyet
Erkek    24.0
Kadın    24.0
Name: Yaş, dtype: float64


In [ ]:
grouped_data = df.groupby('Medeni Durum')['Yaş'].mean()
print( grouped_data)


Medeni Durum
Bekar    24.0
Evli     24.0
Name: Yaş, dtype: float64


In [ ]:
grouped_data = df.groupby('Medeni Durum')['Cinsiyet'].count()
print( grouped_data)

Medeni Durum
Bekar    3
Evli     1
Name: Cinsiyet, dtype: int64


In [ ]:
cinsiyet_medeni_sayim = df.groupby(['Cinsiyet', 'Medeni Durum']).size().unstack()
print(cinsiyet_medeni_sayim)

Medeni Durum  Bekar  Evli
Cinsiyet                 
Erkek           3.0   NaN
Kadın           NaN   1.0


# 2. Temel Makine Öğrenmesi Kavramları

Makine öğrenmesi projelerinde, veri işleme ve model geliştirme sürecinde bazı temel kavramlar çok önemlidir.

## 2.1 Özellik (Feature)
Özellikler, modelin tahmin yapması için kullanılan bağımsız değişkenlerdir.
Örneğin, bir araba fiyat tahmini modelinde, özellikler motor hacmi, yakıt türü, yıl gibi değişkenler olabilir.

## 2.2 Etiket (Label)
Etiket, modelin tahmin etmeye çalıştığı bağımlı değişkendir.
Örneğin, araba fiyat tahmin modelinde, tahmin edilmek istenen 'fiyat' etikettir.

## 2.3 Veri Seti (Dataset)
Modelin eğitilmesi ve değerlendirilmesi için kullanılan verilerin tümüne veri seti denir.
Genelde veri seti, özellikler ve etiketleri içeren bir tablodur.

## 2.4 Eğitim ve Test Seti
Veri seti, modelin başarısını değerlendirebilmek için genellikle ikiye ayrılır: Eğitim ve Test seti.
- Eğitim Seti: Modelin öğrenmesi için kullanılır.
- Test Seti: Modelin performansını değerlendirmek için kullanılır.

In [ ]:
# Titanic veri seti üzerinden bu kavramları uygulamalı olarak gösterelim.
path = '/content/drive/MyDrive/KAIRU/Kurumsal/Acun Medya Eğitimi/datasets/titanic.csv'
titanic_df = pd.read_csv(path)

In [ ]:
# Veri Setini İnceleme
display(titanic_df.head())

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [ ]:
display(titanic_df.tail())

PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male   
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
415         1307         0       3  Saether, Mr. Simon Sivertsen    male   
416         1308         0       3           Ware, Mr. Frederick    male   
417         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
413   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416   NaN      0      0              359309    8.0500   NaN        S  
417   NaN      1      1                2668   22.3583   NaN        C

In [ ]:
titanic_df.shape

(418, 12)

In [ ]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
# Özellikler (Features) ve Etiket (Label) Belirleme
# Burada 'Survived' etiketi modelin tahmin etmeye çalıştığı değişkendir.Bağımlı değişkenim
# Modelin bu etiketi tahmin etmesi için, diğer kolonlar özellik olarak kullanılır.
features = titanic_df[['Pclass', 'Sex', 'Age', 'Fare']]
label = titanic_df['Survived']

display(features.head())
display(label.head())


Pclass     Sex   Age     Fare
0       3    male  34.5   7.8292
1       3  female  47.0   7.0000
2       2    male  62.0   9.6875
3       3    male  27.0   8.6625
4       3  female  22.0  12.2875

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [ ]:
# Özelliklerin İşlenmesi (Örnek: 'Sex' Kolonunu Sayısal Hale Getirme)
# Makine öğrenmesi modelleri sayısal verilerle daha iyi çalışır, bu yüzden 'Sex' kolonunu sayısal hale getiriyoruz.
features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})
display(features.head())


<ipython-input-69-6a588eadd146>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['Sex'] = features['Sex'].map({'male': 0, 'female': 1})


Pclass  Sex   Age     Fare
0       3    0  34.5   7.8292
1       3    1  47.0   7.0000
2       2    0  62.0   9.6875
3       3    0  27.0   8.6625
4       3    1  22.0  12.2875

## EKSİK DEĞER

Elbette, eksik değer oranı yüksek olan bir veri setinde farklı doldurma stratejilerini kodlarla birlikte açıklıyorum.

### 1. **Eksik Değeri Yüksek Sütunları Kaldırma**

Eğer bir sütunda çok fazla eksik değer varsa ve bu sütun analiz için kritik değilse, sütunu tamamen kaldırabilirsiniz.

```python
# Eksik değeri %50'den fazla olan sütunları kaldırmak
threshold = 0.5 * len(features)  # Örneğin, veri setinin %50'sinden fazla eksik olan sütunları belirleme
features = features.dropna(thresh=threshold, axis=1)
print(features.head())
```

Bu kod, %50'den fazla eksik değer içeren sütunları kaldırır.

### 2. **Eksik Değeri Yüksek Satırları Kaldırma**

Belirli satırlarda birçok eksik değer varsa, bu satırları veri setinden çıkarabilirsiniz.

```python
# Eksik değeri olan satırları kaldırmak
features = features.dropna(how='any')  # En az bir eksik değeri olan satırları kaldırır
print(features.head())
```

Bu kod, herhangi bir sütunda eksik veri içeren tüm satırları kaldırır.

### 3. **En Sık Görülen Değer (Mod) ile Doldurma**

Kategorik sütunlarda eksik veriyi doldurmak için en sık görülen değeri kullanabilirsiniz.

```python
# Cabin sütunundaki eksik değerleri en sık görülen değer (mod) ile doldurma
features['Cabin'] = features['Cabin'].fillna(features['Cabin'].mode()[0])
print(features['Cabin'].head())
```

Bu kod, `Cabin` sütunundaki eksik değerleri en sık görülen değerle doldurur.

### 4. **Sabit Bir Değer ile Doldurma**

Eğer eksik değerin kendisini özel bir durum olarak ifade etmek istiyorsanız, eksik değerleri sabit bir değerle doldurabilirsiniz.

```python
# Cabin sütunundaki eksik değerleri 'Unknown' olarak doldurma
features['Cabin'] = features['Cabin'].fillna('Unknown')
print(features['Cabin'].head())
```

Bu kod, `Cabin` sütunundaki eksik değerleri `'Unknown'` olarak doldurur.

### 5. **K-NN İmputation (K En Yakın Komşu ile Doldurma)**

`KNNImputer`, eksik değerleri komşu değerlerle doldurur ve sayısal verilerde kullanılır. `KNeighborsClassifier` sınıfı kullanılarak uygulanabilir.

```python
from sklearn.impute import KNNImputer

# KNNImputer kullanarak eksik değerleri doldurma (K = 5)
imputer = KNNImputer(n_neighbors=5)
features[['Age', 'Fare']] = imputer.fit_transform(features[['Age', 'Fare']])
print(features[['Age', 'Fare']].head())
```

Bu kod, `Age` ve `Fare` sütunlarındaki eksik değerleri komşu değerlerle doldurur. `n_neighbors=5` parametresi, 5 en yakın komşuyu kullanarak doldurulacağını belirtir.

### 6. **Makine Öğrenmesi Tabanlı Doldurma (Örneğin, Regresyon ile Tahmin)**

Eksik değerleri tahmin etmek için bir regresyon modeli kullanabilirsiniz. Eksik değerlerin olduğu sütunu bağımlı değişken olarak seçip, diğer sütunları bağımsız değişken olarak kullanabilirsiniz.

Örneğin, `Age` sütunundaki eksik değerleri diğer değişkenlerle tahmin etmek için bir basit regresyon modeli kurabilirsiniz:

```python
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Age sütunundaki eksik olmayan satırları ayırıyoruz
train_data = features[features['Age'].notnull()]
test_data = features[features['Age'].isnull()]

# Bağımsız değişkenler (diğer sütunlar) ve bağımlı değişken (Age) olarak ayırma
X_train = train_data.drop(columns=['Age'])
y_train = train_data['Age']
X_test = test_data.drop(columns=['Age'])

# Basit bir lineer regresyon modeli oluşturup eğitiyoruz
model = LinearRegression()
model.fit(X_train, y_train)

# Eksik Age değerlerini tahmin ediyoruz ve dolduruyoruz
features.loc[features['Age'].isnull(), 'Age'] = model.predict(X_test)
print(features['Age'].head(10))
```

Bu kod, `Age` sütunundaki eksik değerleri diğer değişkenlerle tahmin eder ve doldurur.

### 7. **Eksik Değer İçeren Özelliklerin Özel İşaretlenmesi**

Eksik değerleri bir bilgi olarak korumak istiyorsanız, eksik olup olmadığını işaretleyebilirsiniz. Bu, özellikle eksikliğin kendisinin anlam taşıdığı durumlarda faydalıdır.

```python
# Cabin bilgisinin eksik olup olmadığını belirten bir sütun ekleme
features['Cabin_Missing'] = features['Cabin'].isnull().astype(int)
print(features[['Cabin', 'Cabin_Missing']].head())
```

Bu kod, `Cabin` sütunundaki eksik veriyi `1` (eksik) veya `0` (eksik değil) şeklinde işaretleyen yeni bir sütun ekler.

---

### Özetle
Bu kodlar, eksik değer oranı yüksek olan veri setlerinde kullanılabilecek farklı stratejileri gösterir:

- **Sütun veya satır kaldırma**: Veri kaybını göze alarak gereksiz verileri çıkarır.
- **Mod veya sabit bir değerle doldurma**: Basit ve hızlı bir yöntemdir.
- **K-NN veya regresyon ile tahmin**: Eksik veriyi tahmin etmek için kullanılır.
- **Eksiklik işaretleme**: Eksikliğin bir bilgi taşıdığı durumlarda eksikliği korumak için kullanılır.

Her yöntemi ihtiyacınıza göre uyarlayabilir ve analizlerinizi daha sağlıklı hale getirebilirsiniz.

In [ ]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

NOT: get_dummies ve encoder konuları ileride anlatılacaktır.

In [ ]:
# Eksik Değerlerin İşlenmesi
# 'Age' kolonu bazı eksik değerlere sahip olabilir. Bu eksik değerleri yaş ortalaması ile dolduralım.
features['Age'] = features['Age'].fillna(features['Age'].mean())
display(features.head())


<ipython-input-71-2e16935c39ba>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['Age'] = features['Age'].fillna(features['Age'].mean())


Pclass  Sex   Age     Fare
0       3    0  34.5   7.8292
1       3    1  47.0   7.0000
2       2    0  62.0   9.6875
3       3    0  27.0   8.6625
4       3    1  22.0  12.2875

In [ ]:
features.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      1
dtype: int64

## EKSİK DEĞERLERDEN NE ZAMAN KURTULMAM GEREKLİ?

### 1. **Eksik Değeri Çok Olan Sütunları Kaldırma**

Eğer bir sütunda çok fazla eksik değer varsa ve bu sütun analiz için kritik değilse, o sütunu veri setinden tamamen kaldırabilirsiniz. Aşağıda, bir sütundaki eksik veri oranı %50’den fazlaysa bu sütunun kaldırılmasını gösteren bir örnek verilmiştir.

```python
# Kaldırma eşiğini belirliyoruz (%50 eksik veri oranı)
threshold = 0.5 * len(features)  # Toplam satır sayısının %50'si

# Eksik değeri %50'den fazla olan sütunları kaldırma
features = features.dropna(thresh=threshold, axis=1)
print("Eksik değeri %50'den fazla olan sütunlar kaldırıldı:")
print(features.head())
```

Bu kodda:
- `thresh=threshold` parametresi, sütunun en az belirli bir sayıda (bu örnekte toplam satır sayısının %50'si) dolu değer içermesi gerektiğini belirtir.
- `axis=1` ile sütun bazında işlem yapılmasını sağlarız.
  
Bu işlem sonunda, eksik değerin çok fazla olduğu sütunlar veri setinden çıkarılmış olur.

### 2. **Eksik Değeri Çok Olan Satırları Kaldırma**

Eğer belirli satırlarda çok sayıda eksik değer varsa, bu satırları veri setinden çıkarabilirsiniz. Bu durumda, satırda herhangi bir eksik değer varsa veya satırdaki belirli sayıda değerin eksik olduğu durumları kaldırabilirsiniz.

#### Tüm Eksik Değerleri İçeren Satırları Kaldırma

```python
# En az bir eksik değeri olan tüm satırları kaldırma
features = features.dropna(how='any')
print("En az bir eksik değeri olan satırlar kaldırıldı:")
print(features.head())
```

Bu kod, veri setinde herhangi bir sütunda eksik veri içeren tüm satırları kaldırır. `how='any'` parametresi, en az bir eksik değere sahip olan satırları hedef alır.

#### Tüm Değerleri Eksik Olan Satırları Kaldırma

```python
# Sadece tüm değerleri eksik olan satırları kaldırma
features = features.dropna(how='all')
print("Tüm değerleri eksik olan satırlar kaldırıldı:")
print(features.head())
```

Bu kod, sadece tüm sütunlardaki değerlerin eksik olduğu satırları kaldırır. `how='all'` parametresi, yalnızca tüm değerleri eksik olan satırları hedef alır.

#### Belirli Sayıda Eksik Değere Göre Satırları Kaldırma

Örneğin, bir satırda 3 veya daha fazla eksik değer varsa bu satırları kaldırmak isteyebilirsiniz.

```python
# En az 3 eksik değeri olan satırları kaldırma
features = features.dropna(thresh=len(features.columns) - 3)
print("En az 3 eksik değeri olan satırlar kaldırıldı:")
print(features.head())
```

Bu kodda:
- `thresh=len(features.columns) - 3` parametresi, her satırda en az (toplam sütun sayısı - 3) kadar dolu değere sahip olma şartını koyar. Yani, 3 veya daha fazla eksik değeri olan satırları kaldırır.

---

Bu yöntemler eksik veri oranı çok yüksek olan durumlarda veri setini temizlemek için kullanılabilir. Ancak, satır veya sütunları kaldırmak, veri kaybına yol açabilir; bu yüzden bu yöntemleri kullanırken dikkatli olmak önemlidir.

## VERİYİ EĞİTİM VE TEST OLARAK AYIRMA
Veriyi eğitim ve test olarak ikiye bölmek, makine öğrenmesi projelerinde başarılı bir model geliştirmek için temel bir adımdır. Bu işlemin amacı, modelimizin sadece mevcut veriyi "ezberlemekten" ziyade, yeni veriler üzerinde de doğru tahminler yapabilecek kadar "öğrenmesini" sağlamaktır.

### Mantığını Anlayalım

Bir insanın yeni bir konuyu öğrenme sürecini düşünelim. Örneğin, bir öğrenci matematik çalışırken önce ders kitabındaki konuları ve örnekleri inceleyerek öğrenir. Bu süreçte öğrendiği bilgileri uygulamak için soruları çözer. Bu aslında bir "eğitim" sürecidir. Ancak, öğrencinin gerçekten öğrendiğini ve bu bilgiyi yeni sorularda da uygulayabildiğini görmek için, sınavda daha önce karşılaşmadığı sorular sorulur. Sınav, öğrenci için bir testtir ve öğrendiklerini sınamak içindir. Eğer öğrenci sadece ders kitabındaki örnekleri ezberlemişse, sınavdaki farklı sorular karşısında zorlanabilir. Ama konuyu gerçekten anladıysa, sınavda başarılı olur.

Aynı mantıkla, bir makine öğrenmesi modelini de iki aşamada değerlendiririz:
1. **Eğitim aşaması**: Modeli veri üzerinde eğiterek ona "öğrenmesi" için bir fırsat tanırız.
2. **Test aşaması**: Modelin daha önce görmediği veri üzerinde ne kadar doğru tahmin yapabildiğini ölçeriz.

Bu bölme işlemi sayesinde, modelin "ezberleme" yapmadan, verinin genel özelliklerini öğrenip öğrenmediğini değerlendirebiliriz. Yani, modelin "genelleme yapabilme" yeteneğini test etmiş oluruz.

### Neden Bölüyoruz?

Bir modeli değerlendirmek için eğitim verisi yeterli değil çünkü bu veriyle modeli eğitirken, model bu veriyi zaten görmüş olur. Eğer modelimizi sadece eğitim verisiyle test edersek, sonuçlar yanıltıcı olabilir. Model, eğitim verisindeki detaylara aşina olduğu için bu veri üzerinde çok iyi performans gösterebilir. Ama aynı model, gerçek hayatta yeni verilerle karşılaştığında başarısız olabilir. Bu yüzden, modelin daha önce görmediği veriyle (yani test verisiyle) değerlendirilmesi gerekir.

### Özetle

Veriyi eğitim ve test olarak ikiye bölmek:
- Modelin ezberlemesini değil, öğrenmesini sağlamaya çalışır.
- Modelin gerçek dünyada yeni verilerle karşılaştığında da başarılı olup olmadığını değerlendirmemizi sağlar.

Bu bölme işlemi, bir insanın öğrenme sürecindeki pratik yapma ve sınav aşamalarına benzer. Eğitim veri seti, modelin öğrenmesi için kullanılırken, test veri seti modelin performansını değerlendirmek için kullanılır. Bu şekilde, modelin gerçekten öğrendiğini ve yeni veriler üzerinde doğru tahmin yapma yeteneğini ölçebiliriz.

In [ ]:

# Veri Setini Eğitim ve Test Olarak Ayırma
from sklearn.model_selection import train_test_split
#x: bağımsız değişkenler
#y : bağımlı değişken
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=42)

print("\nEğitim ve Test Seti Boyutları:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)


Eğitim ve Test Seti Boyutları:
X_train: (334, 4)
X_test: (84, 4)
y_train: (334,)
y_test: (84,)


Bu satır, makine öğrenmesi modelleri için veriyi eğitim ve test seti olarak ayırmak amacıyla kullanılan `train_test_split` fonksiyonunu gösterir. Bu fonksiyon, veriyi belirli bir oranda rastgele böler ve modelin doğruluğunu değerlendirmek için kullanılır. Bu işlemi parçalara ayırarak açıklayalım:

### Kod Açıklaması

```python
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=42)
```

Bu kod, `features` ve `label` veri setlerini ikiye böler: Eğitim seti ve test seti.

### Parametrelerin Anlamı

1. **`features`**:
   - Modelin öğrenmesi için kullanılan bağımsız değişkenlerin (özelliklerin) bulunduğu veri setidir. Bu, giriş verilerini (input) temsil eder.
   - `features`, modelin tahmin yapması için ihtiyaç duyduğu verilerden oluşur. Örneğin, bir tahmin modelinde yaş, gelir, cinsiyet gibi değişkenler `features` olarak kullanılır.

2. **`label`**:
   - Modelin tahmin etmeye çalıştığı bağımlı değişkendir. Bu, hedef değişkeni (output) temsil eder.
   - `label`, modelin tahmin etmesi istenen değerleri içerir. Örneğin, bir fiyat tahmin modelinde tahmin edilmek istenen fiyat değeri `label` olur.

3. **`test_size=0.2`**:
   - Verinin ne kadarının test setine ayrılacağını belirler. `test_size=0.2`, veri setinin %20'sinin test setine, %80'inin eğitim setine ayrılacağı anlamına gelir.
   - Bu parametre, test setinin büyüklüğünü ayarlamak için kullanılır. Örneğin, `test_size=0.3` olarak ayarlanırsa, veri setinin %30'u test seti olarak ayrılır.

4. **`random_state=42`**:
   - Veriyi bölme işleminin rastgeleliğini kontrol etmek için kullanılan bir parametredir.
   - `random_state` aynı değere ayarlandığında, her çalıştırmada aynı şekilde veri bölünür. Bu, sonuçların tekrarlanabilir olmasını sağlar. Farklı bir sayı değeri verilirse veya tamamen kaldırılırsa, verinin bölünmesi her seferinde farklı olur.
   - `random_state=42` ifadesi, sıklıkla kullanılan bir "rastgele durum" örneğidir; herhangi bir özel anlamı yoktur, sadece belirli bir rastgeleliği garanti eder.

### Döndürülen Değerler

- **`X_train`**:
  - `features` veri setinin eğitim setine ayrılan kısmıdır.
  - Modelin eğitilmesi (fit edilmesi) için kullanılan giriş verilerini (özellikleri) içerir.

- **`X_test`**:
  - `features` veri setinin test setine ayrılan kısmıdır.
  - Model eğitildikten sonra, modelin performansını değerlendirmek için kullanılan giriş verilerini içerir.

- **`y_train`**:
  - `label` veri setinin eğitim setine ayrılan kısmıdır.
  - Modelin öğrenmesi gereken hedef değişkenin değerlerini içerir.

- **`y_test`**:
  - `label` veri setinin test setine ayrılan kısmıdır.
  - Model eğitildikten sonra, modelin tahminlerini gerçek değerlerle karşılaştırmak için kullanılan hedef değişkenin değerlerini içerir.

### Örnek Açıklama

Örneğin, elimizde bir ev fiyat tahmin veri seti olduğunu düşünelim:
- **`features`** sütunları: Evin büyüklüğü, oda sayısı, bulunduğu bölge.
- **`label`** sütunu: Evin satış fiyatı.

Bu kod, veri setini %80 eğitim ve %20 test seti olarak ayırır:
- `X_train` ve `y_train` modelin eğitilmesi için kullanılır.
- `X_test` ve `y_test`, model eğitildikten sonra performansını test etmek için kullanılır.

### Neden Veri Setini Ayırıyoruz?

Veri setini ayırmamızın amacı, modelin performansını objektif bir şekilde değerlendirmektir. Modelin önce `X_train` ve `y_train` verileri üzerinde eğitilmesi sağlanır. Ardından `X_test` ve `y_test` verileri kullanılarak, modelin gerçek veriler üzerinde nasıl tahminler yaptığına bakılır. Bu işlem, modelin gerçek dünyada yeni verilere nasıl yanıt vereceğini simüle etmeye yardımcı olur.

Bu ayrım, modelin sadece eğitim verisine ezber yapmasını (overfitting) önler ve modelin genelleme yeteneğini ölçmemizi sağlar.

## Ödev: Palmer Archipelago Penguins Dataset ile Veri Analizi ve Hazırlık

**Amaç:** Bu ödevde, Penguins veri seti üzerinde veri temizleme ve keşif işlemleri yapacağız.
Eksik değerleri dolduracak, veriyi analiz edeceğiz ve makine öğrenmesi modeline hazırlayacağız.

1. **Veri Setini Yükleyin ve İnceleyin**
**Görev:** Palmer Penguins veri setini yükleyin ve ilk birkaç satırını görüntüleyin. Veri setinin genel yapısını anlamak için satır sayısını, sütun isimlerini ve veri türlerini inceleyin.
**İpucu:** head(), info(), describe() gibi yöntemleri kullanabilirsiniz.

2. **Eksik Değer Analizi**
**Görev:** Veri setinde eksik değer olup olmadığını kontrol edin ve her sütundaki eksik değerlerin sayısını listeleyin.

**İpucu:** isnull().sum() fonksiyonunu kullanabilirsiniz.

3. **Eksik Değerleri Doldurma**
**Görev:** Eksik değerleri uygun yöntemlerle doldurun.
Sayısal sütunlar için ortalama veya medyan ile doldurun.
Kategorik sütunlar için en sık görülen (mod) değeri kullanın.

**İpucu:** fillna() fonksiyonunu kullanabilirsiniz.

4. **Kategorik Veriyi Sayısallaştırma (Encoding)**
**Görev:** Makine öğrenmesi modelinde kullanabilmek için sex sütununu sayısal hale getirin.

**İpucu:** map() veya get_dummies() fonksiyonlarını kullanabilirsiniz.

5. **Veri Setini Eğitim ve Test Olarak Ayırma**
**Görev:** species sütununu hedef değişken (label), diğer sütunları ise özellik (feature) olarak belirleyin. Veri setini %80 eğitim ve %20 test seti olarak ayırın.

**İpucu:** train_test_split fonksiyonunu kullanabilirsiniz.

6. **Eğitim ve Test Setinin Boyutlarını Kontrol Edin**
**Görev:** Eğitim ve test setlerinin boyutlarını ekrana yazdırarak ayırma işleminin doğru yapıldığını doğrulayın.







## ÖDEV DATASET HİKAYESİ
**Palmer Archipelago Penguins Dataset** (Palmer Penguen Veri Seti), Palmer Archipelago bölgesindeki üç farklı penguen türü hakkında biyometrik veriler içeren bir veri setidir. Bu veri seti, penguenlerin türlerini tanımlamak için kullanılır ve özellikle makine öğrenmesi, veri analizi ve görselleştirme eğitimleri için popülerdir. **Palmer Archipelago** ise, Antarktika'nın kuzey ucunda bulunan bir takımadadır ve burada birçok penguen kolonisi bulunur.

Veri seti, Palmer Station (Palmer İstasyonu) bölgesinde yaşayan üç penguen türünden toplanan verilerden oluşur: **Adelie**, **Chinstrap** ve **Gentoo**. Bu üç tür, görünüş ve boyut olarak birbirinden farklıdır ve veri seti, bu türler arasındaki farkları analiz etmek için kullanılır.

### Veri Setinin Hikayesi ve Amacı

Palmer Archipelago Penguins Dataset, farklı penguen türlerinin fiziksel özelliklerini kullanarak bu türleri sınıflandırmayı amaçlar. Penguenlerin türleri, yaşadıkları ortam ve boyutları hakkında bilgi vererek araştırmacıların bu canlıları daha iyi tanımasını sağlar. Bu veri seti, özellikle bilim insanlarının ve öğrencilerin, biyolojik türler arasındaki farklılıkları anlamaları ve makine öğrenmesi gibi tekniklerle veri analizi becerilerini geliştirmeleri için idealdir.

Veri seti, genellikle **Iris veri setine** bir alternatif olarak sunulmaktadır, çünkü daha fazla biyolojik çeşitlilik ve daha karmaşık analizlere olanak tanır. Aynı zamanda görselleştirme açısından da çeşitli ilişkileri incelemek için idealdir.

### Veri Setindeki Özellikler (Feature'lar)

Veri setinde her bir penguen için aşağıdaki özellikler bulunmaktadır:

1. **species**:
   - **Açıklama**: Penguenin türü. Bu hedef değişken olup, sınıflandırma için kullanılır.
   - **Değerler**: `'Adelie'`, `'Chinstrap'`, `'Gentoo'`
   - **Tip**: Kategorik

2. **island**:
   - **Açıklama**: Penguenin yaşadığı ada. Bu özellik, penguenlerin farklı coğrafi konumlarına göre değişiklik gösterebilir.
   - **Değerler**: `'Biscoe'`, `'Dream'`, `'Torgersen'`
   - **Tip**: Kategorik

3. **bill_length_mm**:
   - **Açıklama**: Penguenin gaga uzunluğu (milimetre cinsinden). Gaga uzunluğu, türler arasında değişiklik gösterebileceğinden sınıflandırma için önemli bir özellik olabilir.
   - **Tip**: Sayısal (float)

4. **bill_depth_mm**:
   - **Açıklama**: Penguenin gaga derinliği (milimetre cinsinden). Gaga derinliği de penguen türlerinin tanımlanmasında yardımcı olabilir.
   - **Tip**: Sayısal (float)

5. **flipper_length_mm**:
   - **Açıklama**: Penguenin yüzgeç uzunluğu (milimetre cinsinden). Yüzgeç uzunluğu, penguen türleri arasında farklılık gösterebilir.
   - **Tip**: Sayısal (float)

6. **body_mass_g**:
   - **Açıklama**: Penguenin vücut kütlesi (gram cinsinden). Türler arasında vücut kütlesi önemli bir ayırt edici özellik olabilir.
   - **Tip**: Sayısal (float)

7. **sex**:
   - **Açıklama**: Penguenin cinsiyeti. Cinsiyet, penguenlerin bazı özelliklerini etkileyebilir, ancak tüm veri noktalarında cinsiyet bilgisi bulunmamaktadır.
   - **Değerler**: `'Male'`, `'Female'`
   - **Tip**: Kategorik

8. **year**:
   - **Açıklama**: Verinin toplandığı yıl. Bu özellik, yıllar arasındaki farklılıkları incelemek için kullanılabilir.
   - **Tip**: Sayısal (integer)

### Veri Setindeki Hedef (Target) Değişken: LABEL:Bağımlı Değişken

Bu veri setinde **hedef değişken (label)** `species` sütunudur. Bu özellik, her bir penguenin türünü belirtir ve sınıflandırma modelleriyle bu türleri tahmin etmek için kullanılır.

### Veri Seti Üzerinde Yapılabilecek Çalışmalar

- **Sınıflandırma**: Üç penguen türünü (Adelie, Chinstrap, Gentoo) özelliklere göre sınıflandırmak için makine öğrenmesi modelleri eğitilebilir.
- **Keşifsel Veri Analizi**: Penguen türlerine göre boyut farklılıklarını analiz ederek özellikler arasındaki ilişkileri görselleştirme.
- **Eksik Veri Doldurma**: Eksik değerler bulunan `sex` gibi özelliklerde eksik değerleri doldurma ve bu süreci yönetme.
- **Korelasyon Analizi**: Özellikler arasındaki ilişkileri inceleyerek, hangi özelliklerin sınıflandırmada daha belirleyici olduğunu analiz etme.

Bu veri seti, hem biyolojik hem de teknik açıdan değerli bilgiler sağlar ve veri bilimi öğrenenler için birçok farklı analiz fırsatı sunar. Öğrenciler, bu veri seti üzerinde çalışarak veri temizleme, özellik mühendisliği, görselleştirme ve sınıflandırma gibi temel veri bilimi becerilerini geliştirebilirler.